# Лабораторная работа №3. NumPy

Выполнил студент группы 12002209 Телятников Максим Евгеньевич

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [5]:
array = np.random.randint(0, 100, size=(10, 10))

print("Массив 10x10:")
print(array)

min_value = np.min(array)
max_value = np.max(array)

print(f"\nМинимальное значение в массиве: {min_value}")
print(f"Максимальное значение в массиве: {max_value}")

Массив 10x10:
[[24 70 43 46 34 98 35 66 13 73]
 [ 6 24 70  9 60 82 17 93 74 38]
 [ 4 76 38 88 85 66 64  1 92 87]
 [12 10 10 26 25 92  9 74 72 83]
 [92 50 64 80 85 21  2 19 75 36]
 [53 68 94 57 25 34 75 95 51 46]
 [39 77 34 82 84 90 52 85 86 72]
 [67 73  3 97 71 63 77 49 57  3]
 [89 22 24 16 62  7 69 61 37 38]
 [63 57 32 66 53 71 83 35 24 20]]

Минимальное значение в массиве: 1
Максимальное значение в массиве: 98


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [6]:

chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print("Шахматная доска 8x8:")
print(chessboard)

Шахматная доска 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [14]:
z = np.arange(11)

z[(z > 3) & (z < 8)] *= -1

print("Массив после изменения знака:")
print(z)

Массив после изменения знака:
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее значение строки матрицы и вычесть его из каждого элемента строки

In [16]:
z = np.random.rand(5, 10)

row_means = np.mean(z, axis=1, keepdims=True)

z_centered = z - row_means

print("Исходная матрица:")
print(z)
print("\nСредние значения строк:")
print(row_means)
print("\nМатрица после вычитания среднего:")
print(z_centered)

Исходная матрица:
[[0.28786673 0.56884033 0.79970234 0.95462008 0.03565488 0.33487283
  0.04008391 0.2343423  0.09618814 0.80256266]
 [0.99153867 0.28751228 0.09982896 0.03397159 0.82810259 0.88683779
  0.71652918 0.85986688 0.44403375 0.52107081]
 [0.43654255 0.74497797 0.6885618  0.90287057 0.25521615 0.65858615
  0.15332846 0.48914995 0.16950731 0.87216483]
 [0.1596183  0.85573277 0.40608029 0.19501476 0.27848874 0.98720411
  0.3841606  0.36528967 0.67862805 0.14987115]
 [0.78157641 0.10047276 0.11943234 0.6358858  0.00235514 0.93604008
  0.57657755 0.73172269 0.05115877 0.8344172 ]]

Средние значения строк:
[[0.41547342]
 [0.56692925]
 [0.53709058]
 [0.44600884]
 [0.47696387]]

Матрица после вычитания среднего:
[[-0.12760669  0.15336691  0.38422892  0.53914666 -0.37981854 -0.08060059
  -0.37538951 -0.18113112 -0.31928527  0.38708924]
 [ 0.42460942 -0.27941698 -0.46710029 -0.53295766  0.26117334  0.31990854
   0.14959993  0.29293763 -0.1228955  -0.04585844]
 [-0.10054802  0.2078874 

5. Поменяйте 1 и 2 строки матрицы

In [17]:
z = np.arange(25).reshape(5,5)

print("Исходная матрица:")
print(z)

z[[0, 1]] = z[[1, 0]]

print("\nМатрица после замены строк:")
print(z)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 представлющий собой точки в декартовой системе координат, преобразовать в полярную

In [20]:
z = np.random.random((10,2))

print("Исходные координаты (x, y):")
print(z)

x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coords = np.column_stack((r, theta))

print("\nПолярные координаты (r, theta):")
print(polar_coords)

Исходные координаты (x, y):
[[4.64683916e-01 4.53708976e-01]
 [6.89106258e-01 3.06757390e-01]
 [1.62873436e-01 6.05238939e-01]
 [4.68605851e-04 8.33293922e-01]
 [4.93146052e-01 4.24693123e-01]
 [5.33128132e-01 8.71295409e-01]
 [4.92383272e-01 6.14618673e-01]
 [6.96941898e-01 8.81790920e-01]
 [1.73867035e-01 4.27338437e-01]
 [9.75463025e-01 3.00577337e-01]]

Полярные координаты (r, theta):
[[0.64944821 0.77344857]
 [0.75429936 0.41881546]
 [0.62677103 1.30791793]
 [0.83329405 1.57023397]
 [0.65081278 0.71095546]
 [1.02146037 1.02168738]
 [0.78752613 0.89537287]
 [1.12395873 0.90195442]
 [0.4613544  1.18438994]
 [1.02072271 0.29890613]]


7. Заменить максимальный элемент массива на ноль

In [23]:
z = np.random.random(10)
print("Исходный массив:")
print(z)

max_index = np.argmax(z)

z[max_index] = 0

print("\nМассив после замены максимального элемента на ноль:")
print(z)

Исходный массив:
[0.3867933  0.47509196 0.51351513 0.0970392  0.60591102 0.66017303
 0.79639064 0.46537369 0.02392952 0.91508364]

Массив после замены максимального элемента на ноль:
[0.3867933  0.47509196 0.51351513 0.0970392  0.60591102 0.66017303
 0.79639064 0.46537369 0.02392952 0.        ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [24]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)

print("Исходный массив z:")
print(z)
print("\nМассив индексов i:")
print(i)

unique_indices = np.unique(i)

z[unique_indices] += 1

print("\nМассив z после добавления 1 к элементам с уникальными индексами:")
print(z)

Исходный массив z:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив индексов i:
[1 9 5 0 9 5 2 2 3 8 9 7 6 6 1 9 1 6 2 9]

Массив z после добавления 1 к элементам с уникальными индексами:
[2. 2. 2. 2. 1. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [25]:
z = np.array([1,2,3,4,5])
new_z = np.zeros(len(z) + (len(z) - 1) * 3, dtype=int)
new_z[::4] = z

print("Исходный вектор:")
print(z)
print("\nНовый вектор с тремя нулями между каждым значением:")
print(new_z)

Исходный вектор:
[1 2 3 4 5]

Новый вектор с тремя нулями между каждым значением:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [27]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив

nearest_index = np.argmin(np.abs(z - v))

nearest_value = z[nearest_index]

print(f"Случайное число v: {v}")
print(f"Ближайшее число в массиве z: {nearest_value} (индекс: {nearest_index})")

Случайное число v: 56.369078255703556
Ближайшее число в массиве z: 56 (индекс: 56)


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3]) #int64 (целые числа)
np.array([1., 4, 2, 5, 3]) #float64 (числа с плавающей точкой, так как есть хотя бы одно число с точкой)
np.array([1, 4, 2, 5, 3], dtype='float128') #float128 (128-битные числа с плавающей точкой)
np.array([1., 4, 2, 5, 3], dtype='complex128') #complex128 (комплексные числа)
np.array([1, 4, 2, 5, 3], dtype ='float64') #float64 (64-битные числа с плавающей точкой)
np.array([1, 4, 2, 5, 3], dtype =int64) #Ошибка
np.array([1, 4, 2, 5, 3], dtype='bool') #bool (логические значения: True/False)
np.array([1, 4, 2, 5, 3], dtype='str') #<U1 (строки длиной 1 символ)
np.array([1, 4, 2, 5, '3']) #<U21 (строки, так как есть хотя бы одна строка)
np.array([1, -4, 2, 0, 1j]) #complex128 (комплексные числа, так как есть мнимая единица 1j)
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' #'41' Потому что элемент с индексом 1 — это строка '4'. Конкатенация строк '4' + '1' дает '41'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] #True Потому что np.array([1, -4, 2, 0, 3], dtype='bool')[3] — это False (0 становится False). Второе выражение np.array([1, -4, 2, 0, 3])[1] — это -4 (не ноль, поэтому True). Оператор or возвращает первое истинное значение
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and #False Потому что np.array([1, -4, 2, 0, 3], dtype='bool')[3] — это False. Оператор and возвращает первое ложное значение np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1] #1 Потому что True преобразуется в 1 при приведении к int64
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] #Ошибка: Невозможно преобразовать комплексное число в int64
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] #'1j' Потому что комплексное число 1j преобразуется в строку '1j'
np.array([1, 4, 2, 5, '3'])[-1] * 3 #'333' Потому что Элемент '3' — это строка. Умножение строки на число повторяет строку
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float) #Массив 3x5, заполненный единицами типа float64
np.full((3, 5), 3.14) #Массив 3x5, заполненный числом 3.14
np.linspace(0, 1, 5) #Массив [0.0, 0.25, 0.5, 0.75, 1.0]
np.diag((1,3,5)) """ Диагональная матрица
[[1, 0, 0],
 [0, 3, 0],
 [0, 0, 5]] """
np.smile((1,3,5)) #Ошибка: Нет такой функции np.smile
np.random.random((3, 3)) #Массив 3x3 со случайными числами от 0 до 1
np.eye(3) """ Единичная матрица 3x3
[[1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]] """
np.empty(3) #Массив из 3 элементов с неинициализированными значениями
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0] #3
X[-1,-1] #7
X[0:1,-1] #[4]
X[0:2,-1] #[4, 8]
X[0:2,0:2] """
 [[3, 5],
  [7, 6]] """
X[1,1:3] #[6, 8]
X[1,:] #[7, 6, 8, 8]
X[1,:] #[7, 6, 8, 8]
X[:,:] #Весь массив X
X[:] #Весь массив X
X[::2,::2] """
 [[3, 2],
  [1, 7]] """
X[0:3:2,0:3:2] """
[[3, 2],
 [1, 7]] """
X[::-1,::-1] """ Массив X, отраженный по строкам и столбцам
[[7, 7, 6, 1],
 [8, 8, 6, 7],
 [4, 2, 5, 3]] """
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2]) #Разделяет массив по строкам на две части: первые 2 строки и оставшиеся строки
np.split(grid, [2], axis=1) #Разделяет массив по столбцам на две части: первые 2 столбца и оставшиеся столбцы
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1] #[1, 2, 3, 3, 2, 1] (конкатенация списков)
    np.array([1, 2, 3]) + np.array([3, 2, 1]) #[4, 4, 4] (поэлементное сложение массивов)
```

**7**. Как в CodeLab измерить время выполнения кода?

Используйте команду %%time или функцию time из модуля time:
```
import time

start_time = time.time()
# Ваш код
end_time = time.time()
print(f"Время выполнения: {end_time - start_time} секунд")
```

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) #58 (сумма всех элементов)
np.sum(M, axis=1) #[14, 29, 21] (сумма по строкам)
np.sum(M, axis=0) #[11, 17, 17, 19] (сумма по столбцам)
np.sum(M, axis=2) #Ошибка: Нет оси 2 в двумерном массиве
np.sum(M, 1) #[14, 29, 21] (аналогично axis=1)
sum(M) #[11, 17, 17, 19] (сумма по столбцам, как np.sum(X, axis=0))
sum(M,1) #Ошибка: sum не принимает аргумент axis
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3 #[False, False, False, True]
X < 3 #[True, True, False, False]
X[X < 3] #[1, 2]
X[X > 3] #[4]
X[X != 3] #[1, 2, 4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

- Производительность: NumPy использует низкоуровневые оптимизации (C/C++ под капотом), что делает операции с массивами быстрее.

- Удобство: NumPy предоставляет множество встроенных функций для работы с массивами (математические операции, статистика, линейная алгебра и т.д.).

- Экономия памяти: NumPy массивы хранят данные более компактно, чем списки Python.

- Векторизация: Операции применяются ко всему массиву сразу, без необходимости писать циклы.

Это преимущество обусловлено использованием непрерывных блоков памяти и оптимизированных низкоуровневых операций.